/**:
  ros__parameters:
    random_walk_timer_period: 0.25
    random_walk_linear: 0.26
    random_walk_angular: 1.82
    random_walk_rot_interval: 3.5
    random_walk_lin_interval_min: 10.0
    random_walk_lin_interval_max: 15.0

    aggregation_max_range: 3.5
    aggregation_min_range: 0.12
    aggregation_front_attraction: 0.5
    aggregation_time_scale: 24.0
    aggregation_base_stay_time: 16.0
    aggregation_group_distance: 0.85
    aggregation_object_reduction: 'MEAN' # MEAN, NEAREST
    aggregation_group_reference_selection: 'MEAN' # MEAN, NEAREST, FARTHEST
    aggregation_object_threshold: 0.2
    aggregation_object_min_width: 2
    aggregation_object_max_width: 8
    aggregation_stay_in_growing_groups: true
    max_translational_velocity: 0.26
    max_rotational_velocity: 1.82

    attraction_max_range: 2.0 # 0.8 on turtle
    attraction_min_range: 0.12
    attraction_front_attraction: -1.0
    attraction_threshold: 1
    attraction_linear_if_alone: 0.0
    attraction_angular_if_alone: 1.0
    max_translational_velocity: 0.26
    max_rotational_velocity: 1.82

    attraction2_max_range: 2.0 # 0.8 on turtle
    attraction2_min_range: 0.12
    attraction2_front_attraction: 1.0
    attraction2_threshold: 1
    attraction2_linear_if_alone: 0.0
    attraction2_angular_if_alone: 1.0
    max_translational_velocity: 0.26
    max_rotational_velocity: 1.82

    dispersion_max_range: 3.5 # 1.2 on turtle,  # max range: 3500mm
    dispersion_min_range: 0.12                # min range: 120mm
    dispersion_front_attraction: 1.0
    dispersion_threshold: 1
    dispersion_linear_if_alone: 0.0
    dispersion_angular_if_alone: 1.0
    dispersion_allow_dynamic_max_range_setting: False
    max_translational_velocity: 0.26 # max: 0.26 m/s
    max_rotational_velocity: 1.82    # max: 1.82 rad/s

    magnetometer_target_direction_x: 80.0 # degree
    magnetometer_front_attraction: 0.0
    magnetometer_stop_when_target_direction_reached: True
    magnetometer_allowed_delta_in_target_direction: 20.0 # degree
    magnetometer_rotational_velocity: 0.6  # rad/s
    max_translational_velocity: 0.26 # max: 0.26 m/s
    max_rotational_velocity: 1.82    # max: 1.82 rad/s

    minimalist_flocking_translational_velocity: 0.2
    minimalist_flocking_rotational_left_velocity: 0.2
    minimalist_flocking_rotational_right_velocity: -0.2
    minimalist_flocking_drive_timer_period: 0
    minimalist_flocking_zone1_threshold: 0.6 # sim 0.5
    minimalist_flocking_zone2_threshold: 0.6 # sim 0.5
    minimalist_flocking_zone3_threshold: 1.0 # sim 1.5
    minimalist_flocking_zone4_threshold: 1.2 # sim 2.5
    minimalist_flocking_zone2_robot_threshold: 18
    minimalist_flocking_robot_threshold: 4
    minimalist_flocking_zone_borders: [0.7853981634 , 2.3561944902 , 3.926990817, 5.4977871438]
    # global params
    max_range: 1.4 # sim 3.5
    min_range: 0.12

    rat_search_max_range: 3.5
    rat_search_timer_period: 0.1 # every 100ms
    rat_search_color_red: 230.0 # set to 256 to inactivate
    rat_search_color_green: 256.0 # set to 256 to inactivate
    rat_search_color_blue: 256.0 # set to 256 to inactivate
    rat_search_right_distance: 0.54 #0.48
    rat_search_left_distance: 1.5
    rat_search_distance_buffer: 0.125 # 12.5cm
    rat_search_wall_right_degree: 270.0
    rat_search_wall_degree: 100.0 # 100
    rat_search_wall_batch_size: 2.0

    #dispersion_max_range: 3.5 # 1.2 on turtle,  # max range: 3500mm
    #dispersion_min_range: 0.12                  # min range: 120mm
    #dispersion_front_attraction: 1.0
    #dispersion_threshold: 1
    #dispersion_stop_if_alone: True
    max_translational_velocity: 0.26 # max: 0.26 m/s
    max_rotational_velocity: 1.82    # max: 1.82 rad/s

    drive_timer_period: 0.25
    drive_linear: 0.26
    drive_angular: 0.0

    turn_timer_period: 0.25
    turn_linear: 0.0
    turn_angular: 0.26

    


