**ros__parameters:
    aggregation_max_range: 3.5
    aggregation_min_range: 0.12
    aggregation_front_attraction: 0.5
    aggregation_time_scale: 24.0
    aggregation_base_stay_time: 16.0
    aggregation_group_distance: 0.85
    aggregation_object_reduction: 'MEAN' # MEAN, NEAREST
    aggregation_group_reference_selection: 'MEAN' # MEAN, NEAREST, FARTHEST
    aggregation_object_threshold: 0.2
    aggregation_object_min_width: 2
    aggregation_object_max_width: 8
    aggregation_stay_in_growing_groups: true


    attraction_max_range: 2.0 # 0.8 on turtle
    attraction_min_range: 0.12
    attraction_front_attraction: -1.0
    attraction_threshold: 1
    attraction_linear_if_alone: 0.0
    attraction_angular_if_alone: 1.0


        attraction2_max_range: 2.0 # 0.8 on turtle
    attraction2_min_range: 0.12
    attraction2_front_attraction: 1.0
    attraction2_threshold: 1
    attraction2_linear_if_alone: 0.0
    attraction2_angular_if_alone: 1.0


    dispersion_max_range: 1.2 # 1.2 on turtle,  # max range: 3500mm
    dispersion_min_range: 0.12                # min range: 120mm
    dispersion_front_attraction: 0.0
    dispersion_threshold: 1
    dispersion_linear_if_alone: 0.0
    dispersion_angular_if_alone: 1.0
    dispersion_allow_dynamic_max_range_setting: False


      drive_timer_period: 0.25
    drive_linear: 0.26
    drive_angular: 0.0

    magnetometer_target_direction_x: 80.0 # degree
    magnetometer_front_attraction: 0.0
    magnetometer_stop_when_target_direction_reached: True
    magnetometer_allowed_delta_in_target_direction: 20.0 # degree
    magnetometer_rotational_velocity: 0.6  # rad/s


    random_walk_timer_period: 0.25
    random_walk_linear: 0.26
    random_walk_angular: 1.82
    random_walk_rot_interval: 3.5
    random_walk_lin_interval_min: 10.0
    random_walk_lin_interval_max: 15.0

    rat_search_max_range: 3.5
    rat_search_timer_period: 0.1 # every 100ms
    rat_search_color_red: 230.0 # set to 256 to inactivate
    rat_search_color_green: 256.0 # set to 256 to inactivate
    rat_search_color_blue: 256.0 # set to 256 to inactivate
    rat_search_right_distance: 0.54 #0.48
    rat_search_left_distance: 1.5
    rat_search_distance_buffer: 0.125 # 12.5cm
    rat_search_wall_right_degree: 270
    rat_search_wall_degree: 100 # 100
    rat_search_wall_batch_size: 2

    # global params
    max_translational_velocity: 0.26
    max_rotational_velocity: 1.82
    # params discussed dispersion node (master)
    discussed_dispersion_timer_period: 0.25
    discussed_dispersion_discussion_time: 20.0 # 20seconds
    discussed_dispersion_discussion_base_distance: 0.6 # 60cm
    discussed_dispersion_discussion_opinion_multiply: 0.4 # 40cm
    # params dispersion node
    # dispersion_angular_if_alone: 0.0
    # dispersion_allow_dynamic_max_range_setting: True
    # params majority rule node
    majority_rule_choose_start_value_at_random: true
    majority_rule_initial_value: 0 # if majority_rule_choose_start_value_at_random is False use this value
    majority_rule_min_opinion: 0 # [majority_rule_min_opinion,voter_model_max_opinion)
    majority_rule_max_opinion: 3 # [majority_rule_min_opinion,voter_model_max_opinion)
    majority_rule_timer_period: 5.0 # in sec

    voter_model_choose_start_value_at_random: true
    voter_model_initial_value: 0 # voting_model_choose_start_value_at_random is False use this value
    voter_model_min_opinion: 0 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_max_opinion: 5 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_timer_period: 2.0 # in sec


    voter_model_with_limiter_number_of_near_robots: 3
    voter_model_with_limiter_choose_start_value_at_random: true
    voter_model_with_limiter_initial_value: 0 # voting_model_choose_start_value_at_random is False use this value
    voter_model_with_limiter_min_opinion: 0 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_with_limiter_max_opinion: 2 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_with_limiter_timer_period: 5.0 # in sec
    voter_model_with_limiter_required_dDm_to_be_near: -50
    voter_model_with_limiter_wifi_interface_name: ad0
