**ros__parameters:
    aggregation_max_range: 1.5
    aggregation_min_range: 0.05
    aggregation_front_attraction: 0.1
    aggregation_time_scale: 30.0
    aggregation_base_stay_time: 20.0
    aggregation_group_distance: 0.08
    aggregation_object_reduction: 'MEAN' # MEAN, NEAREST
    aggregation_group_reference_selection: 'MEAN' # MEAN, NEAREST, FARTHEST
    aggregation_object_threshold: 0.0
    aggregation_object_min_width: 1
    aggregation_object_max_width: 1
    aggregation_stay_in_growing_groups: true
    max_translational_velocity: 0.12
    max_rotational_velocity: 3.5714285714285716

    attraction_max_range: 0.15 # 0.8 on turtle
    attraction_min_range: 0.05
    attraction_front_attraction: 0.1
    attraction_threshold: 0
    attraction_linear_if_alone: 0.0
    attraction_angular_if_alone: 0.2
 

        attraction2_max_range: 0.15 # 0.8 on turtle
    attraction2_min_range: 0.05
    attraction2_front_attraction: 0.1
    attraction2_threshold: 0
    attraction2_linear_if_alone: 0.0
    attraction2_angular_if_alone: 0.2


        beeclust_max_range: 1.5
    beeclust_min_range: 0.05
    beeclust_max_luminance: 5000.0
    beeclust_min_luminance: 1.0
    beeclust_max_timer_period: 4500.0
    beeclust_scale_constant: 100.0
    beeclust_front_attraction: 0.1
    beeclust_object_reduction: 'MEAN' # MEAN, NEAREST
    beeclust_object_threshold: 0.0
    beeclust_object_min_width: 1
    beeclust_object_max_width: 7



    dispersion_max_range: 0.15    # max range: 3500mm
    dispersion_min_range: 0.05                 # min range: 120mm
    dispersion_front_attraction: 0.1
    dispersion_threshold: 0
    dispersion_linear_if_alone: 0.0
    dispersion_angular_if_alone: 0.2


        drive_timer_period: 0.25
    drive_linear: 0.1 # 0.22
    drive_angular: 0.0


    line_avoidance_max_timer_count: 100000
 

    magnetometer_target_direction_x: 80.0 # degree
    magnetometer_front_attraction: 0.0
    magnetometer_stop_when_target_direction_reached: true
    magnetometer_allowed_delta_in_target_direction: 20.0 # degree
    magnetometer_rotational_velocity: 0.6  # rad/s
    max_translational_velocity: 0.22 
    max_rotational_velocity: 2.84    

    minimalist_flocking_translational_velocity: 0.2
    minimalist_flocking_rotational_left_velocity: 2.0
    minimalist_flocking_rotational_right_velocity: -2.0
    minimalist_flocking_drive_timer_period: 0
    minimalist_flocking_zone1_threshold: 0.05
    minimalist_flocking_zone2_threshold: 0.05
    minimalist_flocking_zone3_threshold: 0.08
    minimalist_flocking_zone4_threshold: 0.08
    minimalist_flocking_zone2_robot_threshold: 7
    minimalist_flocking_robot_threshold: 7
    minimalist_flocking_zone_borders: [0.01745329, 2.35619449, 3.92699082, 6.26573201]
    # global params
    max_range: 0.15
    min_range: 0.03

    random_walk_timer_period: 0.25
    random_walk_linear: 0.2
    random_walk_angular: 3.5714285714285716
    random_walk_rot_interval: 2.0
    random_walk_lin_interval_min: 10.0
    random_walk_lin_interval_max: 15.0


    rat_search_max_range: 3.5
    rat_search_timer_period: 0.1 # every 100ms
    rat_search_color_red: 230.0 # set to 256 to inactivate
    rat_search_color_green: 256.0 # set to 256 to inactivate
    rat_search_color_blue: 256.0 # set to 256 to inactivate
    rat_search_right_distance: 0.54 #0.48
    rat_search_left_distance: 1.5
    rat_search_distance_buffer: 0.125 # 12.5cm
    rat_search_wall_right_degree: 270
    rat_search_wall_degree: 100 # 100
    rat_search_wall_batch_size: 2



    
    # params discussed dispersion node (master)
    discussed_dispersion_timer_period: 0.25
    discussed_dispersion_discussion_time: 20.0 # 20seconds
    discussed_dispersion_discussion_base_distance: 0.09 # 60cm
    discussed_dispersion_discussion_opinion_multiply: 0.05 # 40cm
    # params dispersion node
    dispersion_behavior_if_alone: TURN
    dispersion_allow_dynamic_max_range_setting: True
    # params majority rule node
    majority_rule_choose_start_value_at_random: true
    majority_rule_initial_value: 0 # if majority_rule_choose_start_value_at_random is False use this value
    majority_rule_min_opinion: 0 # [majority_rule_min_opinion,voter_model_max_opinion)
    majority_rule_max_opinion: 3 # [majority_rule_min_opinion,voter_model_max_opinion)
    majority_rule_timer_period: 5.0 # in sec


    voter_model_choose_start_value_at_random: true
    voter_model_initial_value: 0 # voting_model_choose_start_value_at_random is False use this value
    voter_model_min_opinion: 0 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_max_opinion: 5 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_timer_period: 2.0 # in sec

    voter_model_with_limiter_number_of_near_robots: 3
    voter_model_with_limiter_choose_start_value_at_random: true
    voter_model_with_limiter_initial_value: 0 # voting_model_choose_start_value_at_random is False use this value
    voter_model_with_limiter_min_opinion: 0 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_with_limiter_max_opinion: 2 # [voter_model_min_opinion,voter_model_max_opinion)
    voter_model_with_limiter_timer_period: 5.0 # in sec
    voter_model_with_limiter_required_dDm_to_be_near: -50
    voter_model_with_limiter_wifi_interface_name: ad0
